#!/bin/bash

. /etc/skel/setup-scripts/create-ssh-keys || exit 1
cd ~/.ssh || exit 1

name="$USER@$HOSTNAME"
link=true

outfile="id_ed25519_${name}"
create_ssh_key_ed25519 $name $outfile $link

#outfile="id_rsa_${name}"
#create_ssh_key_rsa $name $outfile $link

