#!/bin/bash
cd /etc/ssh || exit 1
. /etc/skel/setup-scripts/create-ssh-keys || exit 1

name="hostkey@$HOSTNAME"
link=true

outfile="ssh_host_rsa_key"
create_ssh_key_rsa $name $outfile $link

outfile="ssh_host_ed25519_key"
create_ssh_key_ed25519 $name $outfile $link
