#!/bin/bash

current_shell="$(readlink -f /bin/sh)"
target_shell='/bin/bash'

if [[ $current_shell != $target_shell ]]; then
    rm /bin/sh && \
    ln -s $target_shell /bin/sh || \
    echo "failed to set $target_shell as default shell"
fi
