#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"
git pull || { echo "failed to pull"; exit 1; }

while read source target; do
    echo "#####################################################################"
    echo "copy ${source} -> ${target}"
    rsync -avh --partial --progress "$source" "$target"
done <<HERE
/etc/skel/         ./etc/skel/
/etc/skel.obi/     ./etc/skel.obi/
/etc/cron.hourly/  ./etc/cron.hourly/
HERE
git clean -fdxn
git diff --stat
