#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"

while read source; do
    case "$source" in
        *skel*|*cron*)
        ;;
        *)
            echo "ignoring $source"
            continue
        ;;
    esac

    target="/$source"
    user="$(stat --printf %G "$target" 2>/dev/null)"
    group="$user"

    if [[ ${_o_os_mac} == "yes" ]]; then
        if [[ $(id -u) == "0" ]]; then
            user="root"
            group="staff"
        fi
    fi

    targetdir="${target%/*}"
    if ! [[ -d "$targetdir" ]];then
    echo "mkdir -p $targetdir"
        mkdir -p "$targetdir"
    fi

    if [[ -h $source ]]; then
        #copy symlinks into dir
        echo "discoverd symlink switch target to dir"
        target="$targetdir"
    fi

    echo "copy ./${source} -> ${target} ($user)"
    rsync -avhq "$source" "$target" || { echo "operation failed"; exit 1; }

    if [[ -n "$user" ]]; then
        chown -R "$user:$group" "${target}"
    fi

    echo
done < <(git ls-tree --name-only -r HEAD)
