#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"

rsync -avh --partial --progress /etc/skel/     ./skel/
rsync -avh --partial --progress /etc/skel.obi/ ./skel.obi/
