#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"

rsync -avh --partial --progress ./skel/      /etc/skel/
rsync -avh --partial --progress ./skel.obi/  /etc/skel.obi/
