#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"

while read source; do
    case "$source" in
        *skel*|*cron*)
        ;;
        *)
            echo "ignoring $source"
            continue
        ;;
    esac
    target="/etc/$source"
    user="$(stat --printf %G "$target")"
    group="$user"
    if [[ ${_o_os_mac} == "yes" ]]; then
        if [[ $(id -u) == "0" ]]; then
            user="root"
            group="staff"
        fi
    fi
    echo "copy ./${source} -> ${target} ($user)"
    rsync -avh --partial --progress "$source" "$target" && \
    chown -R "$user:$group" "${target}"
done < <(git ls-tree --name-only -r HEAD)
