#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"

while read source; do
    target=~/"${source#*/}"

    case "$source" in
        *vimrc-single-file)
            if [[ -e ~/.vim/vimrc ]]; then
                echo "ignoring (has ~/.vim/vimrc) $source"
                continue
            fi
            target=~/.vimrc
        ;;
        skel\.obi*)
            echo "good"
        ;;
        *)
            echo "ignoring $source"
            continue
        ;;
    esac


    targetdir="${target%/*}"
    if ! [[ -d "$targetdir" ]];then
    echo "mkdir -p $targetdir"
        mkdir -p "$targetdir"
    fi

    if [[ -h $source ]]; then
        #copy symlinks into dir
        echo "discoverd link switch target to dir"
        target="$targetdir"
    fi

    echo "copy ./${source} -> ${target} ($user)"

    rsync -avhq "$source" "$target" || { echo "operation failed"; exit 1; }
    echo

done < <(git ls-tree --name-only -r HEAD)
