#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir"

while read source; do
    case "$source" in
        skel\.obi*)
            echo "good"
        ;;
        *)
            echo "ignoring $source"
            continue
        ;;
    esac

    target=~/"${source#*/}"
    echo "copy ./${source} -> ${target}"
    rsync -avh --partial --progress "$source" "$target"
done < <(git ls-tree --name-only -r HEAD)
