#!/usr/bin/env bash
# Copyright - 2010-2018 - Jan Christoph Uhde <Jan@UhdeJC.com>
# vim:filetype=sh foldmethod=marker foldmarker="{{{,}}}"
# set -o vi

_o_os_linux="no"
_o_os_mac="no"
_o_os_windows="no"

_o_system_ls=/usr/bin/ls
_o_system_tmux=/usr/bin/tmux
_o_system_vim=/usr/bin/vim
_o_system_gnu_grep=/bin/grep
_o_system_gnu_readlink=/bin/readlink
_o_system_mosh=/usr/bin/mosh
_o_system_mosh_server=/usr/bin/mosh_server

case "$(uname)" in
    Linux)
        _o_os_linux="yes"

        # debian in wsl
        if [[ ! -x _o_system_ls && -x /bin/ls ]]; then
            _o_system_ls=/bin/ls
        fi

        find_port(){ netstat -n -l -p "$@"; }
    ;;
    Darwin)
        _o_os_mac="yes"
        if [[ -x /usr/local/bin/gls ]]; then
            _o_system_ls=/usr/local/bin/gls
        else
            _o_system_ls=/bin/ls
        fi
        _o_system_tmux=/usr/local/bin/tmux
        _o_system_vim=/usr/local/bin/vim
        _o_system_gnu_grep=/usr/local/opt/grep/libexec/gnubin/grep
        _o_system_gnu_readlink=/usr/local/opt/coreutils/libexec/gnubin/readlink
        _o_system_mosh=/usr/local/bin/mosh
        _o_system_mosh_server=/usr/local/bin/mosh_server
        PATH="/usr/local/opt/coreutils/libexec/gnubin/:$PATH"

        find_port(){ sudo /usr/sbin/lsof -n -i -P; }
    ;;
esac

case "$(uname)" in
    Linux|Darwin)
        get_own(){ stat -c %U "$(${_o_system_gnu_readlink} -f "$1")"; };
        find_port_clean(){ find_port "$@" 2>&1 | tail -n +3; }
        #mac old - get_own(){ stat -f %Su "$1"; };
    ;;
    *)
        echo "unsupported os"
        get_own(){ echo "unknown user"; };
    ;;
esac

export _o_os_linux
export _o_os_mac
export _o_os_windows

export _o_system_ls
export _o_system_tmux
export _o_system_vim
export _o_system_gnu_grep
export _o_system_gnu_readlink
export _o_system_mosh
export _o_system_mosh_server

export -f get_own
export -f find_port
export -f find_port_clean
