#!/bin/bash
# Copyright - 2010-2018 - Jan Christoph Uhde <Jan@UhdeJC.com>

alias cd..='cd ..'

rsync-pro(){
    rsync -avhH --numeric-ids --partial-dir=rsync-partial-dir --progress "$@"
}

rsync-pro2(){
    rsync -avhH --numeric-ids --partial-dir=rsync-partial-dir --info=progress2 --no-inc-recursive --progress "$@"
}

rsync-pro2short(){
    rsync -avhH --numeric-ids --partial-dir=rsync-partial-dir --info=progress2 --no-inc-recursive "$@"
}

rsync-fat(){
    rsync -rtvhH --modify-window=3 --progress --partial-dir=rsync-partial-dir "$@"
}

ip-external(){
    curl ifconfig.co
}

ip-external-json(){
    if ! jq . <(curl ifconfig.co/json 2>/dev/null); then
        curl ifconfig.co/json
    fi
}

vim(){
    /usr/bin/vim -p "$@"
}

###############################################################################
### FileSystem and Dir Size Commands

## Enable color support of ls and also add handy aliases
case $(uname) in
    Linux*|Darwin*)
        eval "$(TERM=xterm dircolors -b | sed 's/ow=[^:]*/ow=01;93;93/')"
        alias ls='ls --color=always -h'
    ;;
    #Darwin*)
        #alias ls='ls -G -h'
    #;;
    *)
    ;;
esac

alias la='ls -a'
alias ll='ls -l'
alias l='ls -s'
alias lla='ls -s -all'
alias less='less -R'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'

du(){ /usr/bin/du -h "$@" ; }
bigdirs(){ /usr/bin/du -hsx -- * | sort -rh | head -10; }
df(){ /bin/df -h "$@" ; }

alias di='/usr/bin/di -h -s -n -t -f Mfpbst -I ext3,ext4,fuseblk,ntfs'
alias dia='/usr/bin/di -h -s -n -t -f Mfpbst -I ext3,ext4,fuseblk,fuse,tmpfs'
alias dio='/usr/bin/di -h -s -n -t -f MfpbstO -I ext3,ext4,fuseblk,ntfs'

alias mosh='/usr/bin/mosh --server="env MOSH_SERVER_SIGNAL_TMOUT=86400 mosh-server"'

alias bashcheck='shellcheck -x -s bash'

###############################################################################
#admin stuff
alias path='echo -e ${PATH//:/\\n}'
alias systemd-show-runlevel='systemctl list-units --type=target'
# log colorizer
alias ccze='ccze -A'

show_locale(){
    set | grep "^LANG=*"
    set | grep "^LC_*=*"
}

###############################################################################
# grep

grep() {
    ${_o_system_gnu_grep} --colour "$@"
}

bgrep() {
    ${_o_system_gnu_grep} --binary-files=text "$@"
}
egrep() {
    ${_o_system_gnu_grep} -E --colour --binary-files=text "$@"
}

gps(){
    cmd=(
        "${_o_system_gnu_grep}"
        "-E"
        "--colour"
    )
    # grep for process
    # shellcheck disable=SC2009 # use pgrep instead grepping ps
    # shellcheck disable=SC2196 # egrep not standard
    ps aux | \
    grep -v "${cmd[@]}" | \
    "${cmd[@]}" "$@"
}

o_pscg(){ ps xawf -eo pid,user,cgroup,args; }
o_gpscg(){
    # shellcheck disable=SC2196
    pscg | gps "$@"
}

###############################################################################
# type

type-vim(){
    file="$(type "$1" | awk '{print $3}')"
    test -e "$file" && vim "$file"
}

type-less(){
    file="$(type "$1" | awk '{print $3}')"
    test -e "$file" && vim "$file"
}

type-obi(){
    res="$(type "$1")"
    if $?; then
        if [[ "$res" == *aliased* ]]; then
            grep -R "$1" ~/.bashrc.d/*
        fi
    fi
}

###############################################################################
# screen / tmux

screen(){
    #list screen sessions of all users
    if [[ "$1" != "-ls-all" ]]; then
        /usr/bin/screen "$@"
    else
        shopt -s nullglob
        local screens=(/var/run/screen/S-*/*)
        shopt -u nullglob
        if (( ! ${#screens[@]} )); then
            echo "no screen session found in /var/run/screen"
        else
            for s in "${screens[@]#*S-}"; do
                echo "$s"
            done
        fi
    fi
}

tmuxa(){
    ${_o_system_tmux} attach-session -t "$@"
}

tmux(){
    if [[ $1 == "-r" ]]; then
        shift
        ${_o_system_tmux} attach-session "$@"
    elif [[ $1 == "main" ]]; then
        tmuxa "$@"
    elif [[ $1 == "-ls" ]]; then
        shift
        ${_o_system_tmux} list-sessions "$@"
    else
        ${_o_system_tmux} "$@"
    fi
}

tmain(){
    ${_o_system_tmux} attach-session -t main "$@"
}

###############################################################################
#user only
if (( UID != 0 )); then
    alias ifconfig='/sbin/ifconfig'
    alias poweroff='sudo /sbin/poweroff'
    alias halt='sudo /sbin/poweroff'
    alias mmpv='mpv -no-audio'
fi


###############################################################################
#root only
if (( UID == 0 )); then
    update(){
        case $1 in
            d*)
                apt-get update && apt-get dist-upgrade
            ;;
            *)
                apt-get update && apt-get upgrade
            ;;
        esac
    }
fi
