#!/usr/bin/env bash
# Copyright - 2010 - Jan Christoph Uhde <Jan@UhdeJC.com>
## History Commands
HISTFILESIZE=500          # increase history file size (default is 500)

shopt -s cmdhist
export HISTFILE=~/.cache/.bash_history # replace with /dev/null
export HISTIGNORE="&:ls:exit:su*"

# append to the history file, don't overwrite it
shopt -s histappend

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
#HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth # leading space hides commands from history & dupes are irgnored

## hstr configuration
alias hh=hstr                    # hh to be alias for hstr
export HSTR_CONFIG=hicolor       # get more colors
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)

# done in prompt file
# ensure synchronization between Bash memory and history file
#export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"

has_tiocsti="$(hstr --is-tiocsti)"
if [[ "$has_tiocsti" == "y" ]]; then
    # REQUIRES
    # sysctl -w dev.tty.legacy_tiocsti=1
    # sudo sh -c "echo 'dev.tty.legacy_tiocsti=1' > /etc/sysctl.d/9999-legacy-tiocsti.conf"
    if [[ $- =~ .*i.* ]]; then
        bind '"\C-r": "\C-a hstr -- \C-j"'
        bind '"\C-xk": "\C-a hstr -k \C-j"'

        bind -m vi-insert '"\C-r": "\C-u hstr -- \C-j"'
        bind -m vi        '"\C-r": "ddi hstr -- \C-j"'
    fi
else
    ##TODO
    #hstr stops working on linux >=6.2.0 (depending on kernel config)
    #https://github.com/dvorka/hstr/issues/478
    ##TODO END

    function hstrnotiocsti {
        { READLINE_LINE="$( { </dev/tty hstr -- ${READLINE_LINE}; } 2>&1 1>&3 3>&- )"; } 3>&1;
        READLINE_POINT=${#READLINE_LINE}
    }

    if [[ $- =~ .*i.* ]]; then
        bind -x '"\C-r": "hstrnotiocsti"'
    fi

    export HSTR_TIOCSTI=n
fi
