#!/bin/bash
cd /etc/ssh || exit 1

create_key(){
    local name="hostkey@$HOSTNAME"
    local ktype="$1"
    local bits="$2"
    local rounds="$3"

    local cmd=(
        'ssh-keygen'
        '-t' "$ktype"
        '-b' "$bits"
        '-C' "$ktype-$name"
        '-f' "ssh_host_${ktype}_key"
    )

    if [[ -n "$rounds" ]]; then
        cmd+=( '-a' "$rounds" )
    fi

    echo "${cmd[@]}"
    "${cmd[@]}"
}

create_key rsa      4096
create_key ed25519  4096       $((1024*1024))
